version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
      - image: python:3.5.1
    steps:
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - restore_cache:
          key: projectname-master
      - run:
          name: Test command
          command: |
            pwd
            ls -al
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME .
      - save_cache:
          key: dependency-cache
          paths:
            - ~/docker