version: 2
jobs:
  build:
    docker:
      - image: golang:1.6.4
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-docker
    steps:
      - checkout
      - run:
          name: Test command
          command: |
            find ~/ -type f -name Dockerfile
            pwd
            ls -al
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME .
      - save_cache:
          key: dependency-cache
          paths:
            - ~/docker