version: 2
jobs:
  build:
    docker:
      - image: test_web:latest
      - image: python:3.5.1
    working_directory: ~/test
    steps:
      - save_cache:
        key: dependency-cache-{{ checksum "Gemfile.lock" }}
        paths:
          - ~/docker
      - run:
        name: Test Command
        command: pwd