version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test command
          command: |
            find ~/ -type f -name Dockerfile
            pwd
            ls -al
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME .
      - save_cache:
          key: dependency-cache
          paths:
            - ~/docker