on:
  release:
    types: [published]

jobs:
  slack_message:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Markdown Converter
        id: convert
        uses: LoveToKnow/slackify-markdown-action@v1.1.1
        with:
          text: ${{ github.event.release.body }}
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          node <<EOF
          const payload = {
            project: "My Project",
            version: "${{ github.event.release.tag_name }}",
            release_link: "${{ github.event.release.html_url }}",
            changelog: ${{ toJSON(steps.convert.outputs.text) }}
          };
          payload.changelog = payload.changelog.replace(/\n$/, '');

          console.log("payload", payload);

          fetch("${{ vars.SLACK_WEBHOOK_URL }}", {
            method: "POST",
            headers: {
              "Content-Type": "application/json"
            },
            body: JSON.stringify(payload)
          })
          .then(response => {
            if (!response.ok) {
              return response.json().then(err => {
                throw new Error(`Failed to send message: ${err}`);
              });
            }
            console.log("Message sent successfully !");
          })
          .catch(error => {
            console.error("Request error", error.message);
          });
          EOF
