on:
  release:
    types: [published]

jobs:
  slack_message:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Markdown Converter
        id: convert
        uses: LoveToKnow/slackify-markdown-action@v1.1.1
        with:
          text: ${{ github.event.release.body }}
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          CONVERTED_TEXT: ${{ steps.convert.outputs.text }}
        run: |
          node <<EOF
          const payload = {
            channel: "${{ vars.SLACK_CHANNEL_ID }}",
            blocks: [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*[NEW]* My Project - ${{ github.event.release.tag_name }}",
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Show release :rocket:",
                    "emoji": true
                  },
                  "url": "${{ github.event.release.html_url }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":clipboard: tickets JIRA :"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": process.env.CONVERTED_TEXT.replace(/\n$/, '')
                }
              }
            ]
          };

          console.log("payload", payload);

          fetch("https://slack.com/api/chat.postMessage", {
            method: "POST",
            headers: {
              "Authorization": "Bearer ${{ secrets.SLACK_API_TOKEN }}",
              "Content-Type": "application/json"
            },
            body: JSON.stringify(payload)
          })
          .then(response => {
            if (!response.ok) {
              return response.json().then(err => {
                throw new Error(`Failed to send message: ${err}`);
              });
            }
            console.log("Message sent successfully !");
          })
          .catch(error => {
            console.error("Request error", error.message);
          });
          EOF
